# Name of the workflow
name: Release-chloro
on:
  push:
    tags:    
      - 'v*.*.*'
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Install submodule dependencies
        working-directory: ./scripts/build
        run: npm ci
      - name: build
        working-directory: ./
        run: npm run --silent ncc:build
      - name: Compress build
        working-directory: ./
        run: gzip -c ./build/chloro.iife.js > release.gz
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ github.ref_name }}"
          files: ./release.gz
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Chloro"
